/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.GenericDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import tabelas.Contagem;
import tabelas.Doencas;
import tabelas.historico_avaliacao;

/**
 *
 * @author Fernando
 */
public class jFGraficoDoença extends javax.swing.JFrame {
int numeroCidades = 5;
    /**
     * Creates new form jFGraficoDoença
     */
    public jFGraficoDoença() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPGraficoLayout = new javax.swing.GroupLayout(jPGrafico);
        jPGrafico.setLayout(jPGraficoLayout);
        jPGraficoLayout.setHorizontalGroup(
            jPGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPGraficoLayout.setVerticalGroup(
            jPGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFGraficoDoença.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFGraficoDoença.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFGraficoDoença.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFGraficoDoença.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFGraficoDoença().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPGrafico;
    // End of variables declaration//GEN-END:variables
public void gráfico() throws SQLException, ClassNotFoundException, IllegalAccessException, NoSuchMethodException, IllegalArgumentException, InvocationTargetException, InstantiationException{
    GenericDao dao = new GenericDao();
     List Teste = dao.listar(historico_avaliacao.class);  
     
     List Doencas = dao.listar(Doencas.class); 
     List<Doencas> todasDoencas = Doencas;          
     
     List<Doencas> doencasUsadas = new ArrayList();
     List<Contagem> contagemCidades = new ArrayList();
     List<Contagem> ordemGrafico = new ArrayList();
     
// Esse for tem como objetivo descobrir quais as cidades que "nao" tem seu codigo usado/referenciado na tabela Alunos, deixando as que tem referencia em uma List
     for (int i = 0; i < Teste.size(); i++) { 
            
            List<historico_avaliacao> lal = Teste; //Cria uma List de tipo Alunos para poder usar o conteudo da tabela Alunos
            historico_avaliacao test = lal.get(i);
            
            for (int j = 0; j < todasDoencas.size(); j++) {  
                Doencas doen = todasDoencas.get(j);
                if (doen.getcod_doenca()== test.getCod_doenca()) { // Identifica a cidade que foi usada para por esse Aluno e criando um objeto o adiciona a uma List
                    Doencas guarda = new Doencas();
                    guarda.setcod_doenca(test.getCod_doenca());
                    guarda.setnome_doenca(doen.getnome_doenca());
                    doencasUsadas.add(guarda);
                }
            }
        }
    
    // Esse for tem como objetivo contar "quantas" vezes cada cidade foi referenciada na tabela Alunos e guarda as informação em uma List 
     for (int i = 0; i < todasDoencas.size(); i++) { 
         Contagem numero;                        /* instancia um objeto do tipo NumeroCidade, objeto tal que foi criado manualmente para 
                   esse método e contem os parametros numero e nome onde serao colocados o nome da cidade e quantas vezes cada uma foi usada */
         Doencas todas = todasDoencas.get(i);
          int contar = 0; 
            for (int j = 0; j < doencasUsadas.size(); j++) {
                Doencas usadas = doencasUsadas.get(j);
                if (usadas.getcod_doenca() == todas.getcod_doenca()) { // alimenta a variavel cada vez que a cidade encontrada for encontrada
                 contar++; //variavel ira conter quantas vezes a cidade foi usada
                }
            }
           numero = new Contagem();
           numero.setNumero(contar);                            
           numero.setNome_cidade(todas.getnome_doenca());
           contagemCidades.add(numero);                                              
    }
     
  
     
     // esse for tem como objetivo colocar as cidades em sequencia da maior para a menor no grafico 
      for (int s = 0; s < numeroCidades; s++) { //  esse for define quantas cidades irao estar no  grafico
          Contagem teste;
          int aux = 0;
          int pegarLinha = 0;
        
            for (int i = 0; i < contagemCidades.size(); i++) { // for serve para percorrer toda a List que contem as cidades e quantas vezes foram usadas
                boolean seila = true;
                 teste = contagemCidades.get(i);
                  if (aux < teste.getNumero() ) { // if para serve pegar sempre a cidades com maior numero(vezes referenciado na tabela alunos)
                     for (int j = 0; j < ordemGrafico.size(); j++) { 
                          Contagem ordem = ordemGrafico.get(j);
                              if(teste.getNome_cidade().equals(ordem.getNome_cidade())){ //  esse if serve para descobrir se a cidade em questao ja esta adicionada na List do Grafico
                                  seila = false;
                              }
                      } 
                     if (seila) {                             // se parametros forem verdadeiros esse if é executado
                                  aux= teste.getNumero();     
                                  pegarLinha = i;            // pega a linha da List contagemCidades  para depois poder saber qual e a cidade que precisa ser add na outra List
                     }

                  }
              }
            teste= contagemCidades.get(pegarLinha);
            ordemGrafico.add(teste);
      }
      
       DefaultCategoryDataset dataset = new DefaultCategoryDataset();
      // esse for monta o grafico
      for (int i = 0; i < ordemGrafico.size(); i++) {
          Contagem teste = ordemGrafico.get(i);
          System.out.println(teste.getNome_cidade());
          int numero = teste.getNumero();
          dataset.setValue(numero, "", teste.getNome_cidade());
          System.out.println("testeeeeee");
          
           JFreeChart chart = ChartFactory.createBarChart("Pessoas por Cidade", "", "", dataset, PlotOrientation.VERTICAL, false, false, false);
        CategoryPlot catPlot = chart.getCategoryPlot();
        catPlot.setRangeGridlinePaint(Color.BLACK);
        
        ChartPanel qualquercoisa = new ChartPanel(chart);
        qualquercoisa.setSize(jPGrafico.getWidth(),jPGrafico.getHeight());
        qualquercoisa.setVisible(true);
        jPGrafico.removeAll();
        jPGrafico.add(qualquercoisa, BorderLayout.CENTER);
        jPGrafico.revalidate();
        jPGrafico.repaint();
    }
}

}
